### ISSUE TITLE
安卓iframe方法只能唤醒后台进程中的app，并不能正确唤醒

### ISSUE THREAD

**Issue by mrbian** [AlanZhang001/H5CallUpNative#1]
问题如题
经过测试，下面这个方法是好用的
```javascript
location.href = "xueban3://Activity/IndexPage";        // 跳转
setTimeout(() => {
  if(! (document.hidden || document.webkitHidden)){
    location.href = downloadUrl;
  }
},1000);
```

**Comment by AlanZhang001** [comment]
@mrbian 你测试的浏览器及平台是？

**Comment by mrbian** [comment]
qq内置浏览器，chrome，opera，平台是安卓5.0及小米版安卓系统。网址：http://139.129.42.180:3010/xueban3/news/86f3787a-146b-477d-af5c-fd4ed4be6b4c?

**Comment by mrbian** [comment]
qq内置浏览器，chrome，opera，平台是安卓5.0及小米版安卓系统。网址：http://139.129.42.180:3010/xueban3/news/86f3787a-146b-477d-af5c-fd4ed4be6b4c?
