### ISSUE TITLE
浏览器询问是否跳转时选择否会阻止下次唤起

### ISSUE THREAD

**Issue by Yangqin0607** [AlanZhang001/H5CallUpNative#11]
在ios的uc浏览器上，点击按钮唤起时，浏览器会弹框询问是否跳转，如果选择否，再次点击按钮就不再会尝试去唤起app了，请问这个您是怎么解决的呢

**Comment by freeaswind** [comment]
同求一问

**Comment by freeaswind** [comment]
楼上解决了吗？求方案

**Comment by Yangqin0607** [comment]
并没有解决，如果点击了取消，下次再点击就会直接去下载页，在app store或者应用商店可以再选择打开

**Comment by freeaswind** [comment]
Thank you all the same.

**Comment by AlanZhang001** [comment]
抱歉，最近有点忙，找时间研究这个问题。

**Comment by AlanZhang001** [comment]
这个问题，查了很久，暂时没有解决的办法

**Comment by Yangqin0607** [comment]
谢谢

**Comment by renyuns** [comment]
有的 Android 手机第一次拒绝过后就记录设置中了,下一次就不能用了,只有用户清除设置才行
