### ISSUE TITLE
[错误]在Android Chrome浏览器中，版本号在chrome 25+的版本不再支持通过传统schema的方法唤醒APP

### ISSUE THREAD

**Issue by VIGDXX** [AlanZhang001/H5CallUpNative#13]
![image](https://user-images.githubusercontent.com/25626094/49370313-c3c7af00-f72e-11e8-9692-17189eb7a894.png)
https://developer.chrome.com/multidevice/android/intents

**Comment by gaoxuerong** [comment]
> ![image](https://user-images.githubusercontent.com/25626094/49370313-c3c7af00-f72e-11e8-9692-17189eb7a894.png)
> https://developer.chrome.com/multidevice/android/intents

大哥，你应该在陈述下比较好，这样看起来比较清晰

**Comment by gaoxuerong** [comment]
> ![image](https://user-images.githubusercontent.com/25626094/49370313-c3c7af00-f72e-11e8-9692-17189eb7a894.png)
> https://developer.chrome.com/multidevice/android/intents

没错吧

**Comment by gaoxuerong** [comment]
18之前的可以，25之后的不可以，可以用itent

**Comment by gaoxuerong** [comment]
@VIGDXX

**Comment by AlanZhang001** [comment]
合并了一下提交，但是仍然做出了修改。加上这层意思：传统的schema，需要通过明确的手势来触发
@VIGDXX @gaoxuerong

**Comment by xiezht** [comment]
我试了一下，Intent似乎也是需要通过用户的手动触发（比如点击链接）才能够实现app的唤起。而不能使用js的方式触发。

    let link = document.createElement('a')
    link.href = 'intent://something/#Intent;scheme=myapp;package=com.android.myapp;S.browser_fallback_url=someurl;end'
    link.click()

以上方式也是无法再chrome25之后的版本实现app唤起。

**Comment by AlanZhang001** [comment]
![image](https://user-images.githubusercontent.com/9763641/50258816-4f825080-043c-11e9-88cd-ac0dcc955702.png)
这是Android chrome ，是可以的，确保你的intent是对的

**Comment by xiezht** [comment]
请问大佬是使用**手动点击**按钮的方式触发的吗？我使用js触发a.click是不行的

**Comment by AlanZhang001** [comment]
> 请问大佬是使用**手动点击**按钮的方式触发的吗？我使用js触发a.click是不行的

功能我已经封装在当前git的代码中了，也发布npm：tool-callapp，底层就是通过a便签实现的
