### ISSUE TITLE
请问怎么添加pc，mac版本的跳转

### ISSUE THREAD

**Issue by Yizo** [AlanZhang001/H5CallUpNative#15]

**Comment by AlanZhang001** [comment]
功能仅限于移动端唤起 app；对于mac，pc的版本，不支持；唤起的核心逻辑是唤起app的时候，浏览器会被置于后台进程，settimeout延时变慢，pc端桌面上可以同时显示浏览器和app，不适用于当前逻辑。
通常的做法是，判断当前是pc，mac的时候，引导下载
