### ISSUE TITLE
react 导入npm install tool-callapp --save 后报错

### ISSUE THREAD

**Issue by BobbySir** [AlanZhang001/H5CallUpNative#16]
通过 https://github.com/facebook/create-react-app  一件配置react后，执行npm install tool-callapp  启动项目报错

![9EC62DC4305D4A0DDF8C5F848B2AC7F2](https://user-images.githubusercontent.com/17491400/57870765-5ae67600-783a-11e9-9a3c-aa702a566034.jpg)

![image](https://user-images.githubusercontent.com/17491400/57870651-14911700-783a-11e9-8988-d66a1d75f41c.png)

**Comment by AlanZhang001** [comment]
![image](https://user-images.githubusercontent.com/9763641/57992077-eaaf4d00-7ae4-11e9-90b5-f0e99b463c22.png)
框处的内容可以看出，安装是没有问题的。问题在于你启动报错了。可以从react-scripts  start着手去查，或者直接写死react-scripts 的bin路径启动试试，类似  ./xxx/xxx/.bin/react-scripts.js start

**Comment by BobbySir** [comment]
> ![image](https://user-images.githubusercontent.com/9763641/57992077-eaaf4d00-7ae4-11e9-90b5-f0e99b463c22.png)
> 框处的内容可以看出，安装是没有问题的。问题在于你启动报错了。可以从react-scripts start着手去查，或者直接写死react-scripts 的bin路径启动试试，类似 ./xxx/xxx/.bin/react-scripts.js start

好的非常感谢，我才看到消息，我去尝试一下。
