### ISSUE TITLE
希望将package.json的 dependencies里面和开发相关的引用放到devDependencies中。

### ISSUE THREAD

**Issue by littleVege** [AlanZhang001/H5CallUpNative#17]
希望将package.json的 dependencies里面和开发相关的引用放到devDependencies中。
现在npm install的时候会因为eslint install时的node版本检测，导致在某些版本的node中无法安装。只能使用 --ignore-engines 取消npm的检测。

涉及到的npm包: 

```
    "eslint": "^5.6.1",
    "webpack": "^3.1.0",
    "uglifyjs-webpack-plugin": "^1.0.1"
```

**Comment by AlanZhang001** [comment]
谢谢，建议已采纳，最新版本 tool-callapp@1.0.2
