### ISSUE TITLE
微博里面不能跳转到下载页面，请问怎么处理？

### ISSUE THREAD

**Issue by leeycode** [AlanZhang001/H5CallUpNative#6]
安卓手机可以正常跳转到下载，ios不能！

**Comment by AlanZhang001** [comment]
微博里面未做测试和研究，IOS上，是建议使用Universal links这个协议来唤醒APP的（需ios端实现这个协议），普通shcema在ios上其实限制挺多的，特别是各种app的webview中，毕竟webview不是一个标准的浏览器。

**Comment by AlanZhang001** [comment]
发了新版本，微博里面做了处理，直接跳转到下载页
