### ISSUE TITLE
请问混合开发目前可以实现么？

### ISSUE THREAD

**Issue by YuyangHYY** [AlanZhang001/H5CallUpNative#7]
我使用ionic开发的手机应用 目前可以做到从应用分享出去的webview唤醒双平台app么？
或者您那边有什么好的解决方案么？主要是做宣传用，让分享出去的webview提示下载就行，不用做判断用户是否下载（在微信分享中）
我有想过直接加下载地址在html_content那边 可是如果加在那里，手机应用中也同样拿的html_content，所以应用中也会出现下载地址，所以这个解决方案可能不是很好，不知道您那边有什么建议么

**Comment by AlanZhang001** [comment]
你好，可能我们的理解不太一样，没太懂你这里提的问题。能解释清楚一些么
1. 从应用分享出去的webview：这个是指什么？webview怎么会被分享出去？
2. 我有想过直接加下载地址在html_content那边 可是如果加在那里，手机应用中也同样拿的html_content：这里的手机应用是指什么？

**Comment by YuyangHYY** [comment]
总体来说就是，ionic能实现么。。。。

**Comment by AlanZhang001** [comment]
抱歉，没实践过
