### ISSUE TITLE
微信里h5页面唤起app,如果没有唤起会直接跳到了404页面，怎么弄啊

### ISSUE THREAD

**Issue by Marco-ding** [AlanZhang001/H5CallUpNative#8]
微信里h5页面唤起app,如果没有唤起会直接跳到了404页面，怎么弄啊，我用的window.location.href来跳转的，如果有app可以正常唤起，没有就会跳到404页面

**Comment by Marco-ding** [comment]
补充：是ios上出现这种问题

**Comment by AlanZhang001** [comment]
1. H唤醒本身不是可靠的，只是尝试去唤醒
2. 不建议使用location.href来调整，不利于页面的体验。建议用隐藏的iframe或者a标签
