### ISSUE TITLE
android和ios协议为什么用一个字段PROTOCAL？

### ISSUE THREAD

**Issue by nickrogit** [AlanZhang001/H5CallUpNative#9]
android和ios协议为什么用一个字段PROTOCAL？不用分开写么？
包括应用商店的下载地址都取的同一个字段config.failUrl

**Comment by AlanZhang001** [comment]
嗯，这个地方我代码里面写了默认的下载地址，区分了android和iOS，如果调用的时候有指定，就统一使用指定的地址。
![image](https://user-images.githubusercontent.com/9763641/35148610-e0f6f3a0-fd4d-11e7-8211-dc22cb0086e1.png)

这个地方可以根据自己的APP来适量修改封装代码的。因为每个APP太不一样，所以只是提供了大概的代码，开发者在使用时需要根据自己的app适量定制化。
![image](https://user-images.githubusercontent.com/9763641/35148651-0186cdde-fd4e-11e7-8c5a-64299ccfe1ea.png)

应用商城像腾讯应用宝，下载地址是一样的。

**Comment by nickrogit** [comment]
苹果商店的就不一样哦。我是觉得既然封装起来，把相关接口暴露就不要再让使用者修改了，更好一些，因为逻辑都是一样的，我自己再优化优化吧，谢谢。
